export interface IProposalModel {
    SelectedAnswers?: {
        QuestionId: number;
        OptionId: number;
    }[]
    CoverTypeId: number
    CoverType: string
    CubicCapacity: number
    IDV: number
    MinPrice: number
    MaxPrice: number
    FuelType: string
    MFGYear: string
    ModelID: number
    Model: string
    SeatingCapacity: number
    VariantID: number
    Variant: string
    PolicyType: string
    NCBPer: number
    RTOID: number
    PreviousPolicyType: number
    PreviousPolicyNo: string
    ICList: string
    PreviousCoverTypeID: number
    ODDiscount: string
    IsHandiCapped: boolean
    ChassisNo: string
    PolicyEffectiveDate: string
    InvoiceDate: string
    IsExshowroomUpdated: number
    IsTransferCase: number
    InsuranceId: number
    ProductID: number
    ProposalID: number
    IsProposalSaved: number
    ElectricalAmount: number
    NElectricalAmount: number
    IsAA: boolean
    IsAntiTheft: boolean
    VoluntaryDisc: number
    SelectedAddon: string
    QuotationNo: string
    PREV_NCB: number
    ClaimTaken: number
    IsSendQuoteEnable: number
    EMI_Amount: number
    RTI_Amount: number
    RENEW_IDV: number
    ExShowroomPrice: number
    IsFirstPageRequest: number
    IsOnlineQuote: number
}
