export type NcbCarryFrwrd={
PREV_IS_VISOF_POLICY: number;
 PREV_IS_NONVISOF_POLICY: number;
 PREV_VEH_CHASSIS_NO: string;
 PREV_VEH_ENGINE_NO: string;
 PREV_VEH_MODEL: string;
 PREV_VEH_VARIANT_NO: string;
 PREV_VEH_MAKE: string;
 PREV_VEH_MANU_YEAR: string;
 PREV_VEH_INVOICEDATE: any;
 PREV_VEH_REG_NO: string;
 PREV_VEH_POLICY_NO: string;
 PREV_VEH_POLICY_NONVISOF: string;
 PREV_VEH_NCB: number;
 PREV_VEH_IC: number;
 PREV_VEH_ISNCBCERTIFICATE: boolean;
 PREV_VEH_ADDRESS: string;
 PREV_VEH_POLICYSTARTDATE: any;
 PREV_VEH_POLICYENDDATE: any;
 PREV_VEH_NCB_EFFECTIVE_DATE: any;
 PREV_VEH_NCB_EFFECTIVE_DATE_NONVISOF: any;
 PRODUCT_NAME: string;


}